bootdo:
server:
   # context-path: /myboot
   session-timeout: 1800
   tomcat:
       max-threads: 1000
       min-spare-threads: 30
   port: 8090
   uri-encoding: utf-8
security:
    basic:
      enabled: false
logging:
  level:
    com.bootdo: debug

  redis:
      host: 47.100.174.228
      port: 6379
      password:
      # 连接超时时间（毫秒）
      timeout: 10000
      pool:
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1024
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
  thymeleaf:
      mode: LEGACYHTML5
      cache: false
  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
  http:
      multipart:
            max-file-size: 30Mb
            max-request-size: 30Mb
  devtools:
      restart:
        enabled: true
aliyun:
     msg:
       accessKeyId: LTAIZVzt34519H5R
       accessKeySecret: PhhStC9Uv6gIJIkOSb1MP0Rg44a8Gt
       templateCode:  SMS_126320150
       signName: 博聚
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.bootdo.**.domain




